AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy an EC2 instance and associate a DNS name via Route 53.

Parameters:
  PublicSubnetId:
    Type: String
    Description: Public subnet ID
    Default: !Ref ExistingSubnetID

  SecurityGroupId:
    Type: String
    Description: Security group ID
    Default: "sg-0196e871c70cf2952"

  InstanceKeyName:
    Type: String
    Description: EC2 key pair name
    Default: "deltext-key"

  GithubRepoUrl:
    Type: String
    Description: GitHub repository URL
    Default: "https://github.com/deltasnet/deltext"

  HostedZoneId:
    Type: String
    Description: Hosted zone ID
    Default: Z01016491ZLUGE5VHFNXM

  DNSName:
    Type: String
    Description: The DNS name to associate with the EC2 instance.
    Default: deltext.dsoftlab.net

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c1c30571d2dae5c9
      InstanceType: t2.medium
      KeyName: !Ref InstanceKeyName
      IamInstanceProfile: GitHubActionsRoleInstanceProfile
      Tags:
        - Key: Name
          Value: deltext-instance
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !Ref PublicSubnetId
          GroupSet:
            - !Ref SecurityGroupId
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 20
            VolumeType: gp2
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt install -y git iptables
          iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8000
          apt-get update -y
          apt-get install -y ca-certificates curl
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update -y
          apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose

  Ec2EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Ec2Instance

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DNSName
      Type: A
      TTL: "300"
      ResourceRecords:
        - !Ref Ec2EIP

Outputs:
  InstanceId:
    Description: The Instance ID of the EC2 instance
    Value: !Ref Ec2Instance

  InstancePublicIp:
    Description: The public IP address of the EC2 instance
    Value: !GetAtt Ec2Instance.PublicIp

  DNSNameOutput:
    Description: The DNS name associated with the EC2 instance
    Value: !Ref DNSName

  InstanceUrl:
    Description: EC2 instance URL
    Value: !Sub "http://${Ec2Instance.PublicIp}"
