---

- name: Make sure the PostgreSQL users are present
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    encrypted: true
    role_attr_flags: "{{ item.flags }}"
    login_host: "127.0.0.1"
    login_port: "{{ postgresql_port }}"
    login_user: "{{ patroni_superuser_username }}"
    login_password: "{{ patroni_superuser_password }}"
    login_db: "postgres"
    state: present
  ignore_errors: true
  loop: "{{ postgresql_users | flatten(1) }}"
  loop_control:
    label: "{{ item.name }}"
  when: postgresql_users is defined and postgresql_users | length > 0
  tags: postgresql_users

- name: Grant roles to users
  community.postgresql.postgresql_membership:
    group: "{{ item.role | default('') }}"
    target_role: "{{ item.name }}"
    login_host: "127.0.0.1"
    login_port: "{{ postgresql_port }}"
    login_user: "{{ patroni_superuser_username }}"
    login_password: "{{ patroni_superuser_password }}"
    state: present
  ignore_errors: true
  loop: "{{ postgresql_users | flatten(1) }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgresql_users is defined
    - postgresql_users | length > 0
    - item.role | default('') | length > 0
  tags: postgresql_users

- name: Copy PostgreSQL app_user.sql file to the target host
  copy:
    src: app_user.sql
    dest: /tmp/app_user.sql
    owner: postgres  # Optional: Set the owner to postgres user
    group: postgres  # Optional: Set the group to postgres
    mode: '0644'

- name: Execute the app_user.sql script on the PostgreSQL server
  community.postgresql.postgresql_script:
    db: postgres
    port: "{{ postgresql_port }}"
    path: /tmp/app_user.sql
    login_host: localhost
    login_user: "{{ patroni_superuser_username }}"
    login_password: "{{ patroni_superuser_password }}"

...
