CREATE ROLE app_user WITH LOGIN PASSWORD 'password';
GRANT CONNECT ON ALL DATABASES TO app_user;
REVOKE CONNECT ON DATABASE template0 FROM app_user;
REVOKE CONNECT ON DATABASE template1 FROM app_user;
REVOKE CONNECT ON DATABASE postgres FROM app_user;

GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON ALL TABLES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON TABLES TO app_user;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_user;